version: 2

sources:
  - name: raw
    database: raw  # Explicitly specify ClickHouse database
    tables:
      - name: raw___insta_aisles  # Must match EXACTLY (3 underscores)
      - name: raw___insta_departments
      - name: raw___insta_order_products_prior
      - name: raw___insta_order_products_train
      - name: raw___insta_orders
      - name: raw___insta_products

  - name: clean
    database: clean  
    tables:
      - name: regrp5_insta_aisles
      - name: regrp5_insta_departments
      - name: regrp5_insta_order_products_prior
      - name: regrp5_insta_order_products_train
      - name: regrp5_insta_orders
      - name: regrp5_insta_products