name: regrp5_insta
version: '1.0.0'
config-version: 2

profile: clickhouse_ftw
model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
log-path: "logs"

models:
  regrp5_insta:
    clean:
      +schema: clean
      +materialized: table
    mart:
      +schema: mart
      +materialized: view